// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY5VyMgHH5Yak65cEn-nOeTgctWKYCIlo',
    appId: '1:334955244642:web:5c2308a16a97c1490bb53b',
    messagingSenderId: '334955244642',
    projectId: 'petsapp-15365',
    authDomain: 'petsapp-15365.firebaseapp.com',
    storageBucket: 'petsapp-15365.firebasestorage.app',
    measurementId: 'G-ZHR6WS2RYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXddsOJgzbr004D8qPtStjBHFmGbwIX4',
    appId: '1:334955244642:android:83702d545bfcacaa0bb53b',
    messagingSenderId: '334955244642',
    projectId: 'petsapp-15365',
    storageBucket: 'petsapp-15365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdk0BnVGDDUFI3wrkwUZB839WrlMzVQfI',
    appId: '1:334955244642:ios:70821be1b8dc84470bb53b',
    messagingSenderId: '334955244642',
    projectId: 'petsapp-15365',
    storageBucket: 'petsapp-15365.firebasestorage.app',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdk0BnVGDDUFI3wrkwUZB839WrlMzVQfI',
    appId: '1:334955244642:ios:70821be1b8dc84470bb53b',
    messagingSenderId: '334955244642',
    projectId: 'petsapp-15365',
    storageBucket: 'petsapp-15365.firebasestorage.app',
    iosBundleId: 'com.example.petshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY5VyMgHH5Yak65cEn-nOeTgctWKYCIlo',
    appId: '1:334955244642:web:2a7d4dc734cfe5670bb53b',
    messagingSenderId: '334955244642',
    projectId: 'petsapp-15365',
    authDomain: 'petsapp-15365.firebaseapp.com',
    storageBucket: 'petsapp-15365.firebasestorage.app',
    measurementId: 'G-W12X287N7W',
  );
}
